branch-defaults:
  default:
    environment: iaso-stg-worker
global:
  application_name: Iaso
  default_ec2_keyname: iaso-eb
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Python 3.9 running
    on 64bit Amazon Linux 2/3.3.1
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
